### ISSUE TITLE
Probable issue with OWLAPI version is pipeline testing 

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_owl#38]
https://travis-ci.org/VirtualFlyBrain/pipeline/builds/308434295#L1420

```
jython /opt/VFB/VFB_owl/src/code/owl2neo/add_anonymous_types.py http://192.168.0.1:7474 neo4j neo4j /opt/VFB/VFB_owl/src/owl/vfb.owl
Traceback (most recent call last):
  File "/opt/VFB/VFB_owl/src/code/owl2neo/add_anonymous_types.py", line 12, in <module>
    vfb = Brain()
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.<init>(OWLOntologyManagerImpl.java:131)
	at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:131)
	at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:118)
	at uk.ac.ebi.brain.core.Brain.<init>(Brain.java:226)
	at uk.ac.ebi.brain.core.Brain.<init>(Brain.java:153)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)
java.lang.NoSuchMethodError: java.lang.NoSuchMethodError: org.semanticweb.owlapi.util.CollectionFactory.createSyncList()Ljava/util/List;
```

Potentially related to: https://stackoverflow.com/questions/26026366/java-lang-nosuchmethoderror-org-semanticweb-hermit-reasoner-initunknown-sour

**Comment by Robbie1977** [comment]
Versions built are here:
https://travis-ci.org/VirtualFlyBrain/pipeline/builds/308434295#L1292
```
/opt/VFB/VFB_owl/lib/Brain-1.5.2-SNAPSHOT.jar
/opt/VFB/VFB_owl/lib/OWLTools-Core-0.2.2-SNAPSHOT.jar
/opt/VFB/VFB_owl/lib/README.md
/opt/VFB/VFB_owl/lib/ant-1.8.2.jar
/opt/VFB/VFB_owl/lib/ant-launcher-1.8.2.jar
/opt/VFB/VFB_owl/lib/antlr-3.2.jar
/opt/VFB/VFB_owl/lib/antlr-runtime-3.2.jar
/opt/VFB/VFB_owl/lib/automaton-1.11-8.jar
/opt/VFB/VFB_owl/lib/axiom-api-1.2.14.jar
/opt/VFB/VFB_owl/lib/axiom-c14n-1.2.14.jar
/opt/VFB/VFB_owl/lib/axiom-dom-1.2.14.jar
/opt/VFB/VFB_owl/lib/axiom-impl-1.2.14.jar
/opt/VFB/VFB_owl/lib/commons-io-2.2.jar
/opt/VFB/VFB_owl/lib/commons-logging-1.1.3.jar
/opt/VFB/VFB_owl/lib/commons-math-2.1.jar
/opt/VFB/VFB_owl/lib/elk-owl-implementation-0.4.2.jar
/opt/VFB/VFB_owl/lib/elk-owl-model-0.4.2.jar
/opt/VFB/VFB_owl/lib/elk-owlapi-0.4.2.jar
/opt/VFB/VFB_owl/lib/elk-reasoner-0.4.2.jar
/opt/VFB/VFB_owl/lib/elk-util-collections-0.4.2.jar
/opt/VFB/VFB_owl/lib/elk-util-common-0.4.2.jar
/opt/VFB/VFB_owl/lib/elk-util-concurrent-0.4.2.jar
/opt/VFB/VFB_owl/lib/elk-util-hashing-0.4.2.jar
/opt/VFB/VFB_owl/lib/elk-util-io-0.4.2.jar
/opt/VFB/VFB_owl/lib/elk-util-logging-0.4.2.jar
/opt/VFB/VFB_owl/lib/expression-materializing-reasoner-0.0.5.jar
/opt/VFB/VFB_owl/lib/factplusplus-1.5.2.jar
/opt/VFB/VFB_owl/lib/graphdraw-0.0.1-SNAPSHOT.jar
/opt/VFB/VFB_owl/lib/gson-2.2.4.jar
/opt/VFB/VFB_owl/lib/guava-17.0.jar
/opt/VFB/VFB_owl/lib/jaxen-1.1.4.jar
/opt/VFB/VFB_owl/lib/jcel.core-0.15.0.jar
/opt/VFB/VFB_owl/lib/jcel.ontology-0.15.0.jar
/opt/VFB/VFB_owl/lib/jcel.owlapi-0.15.0.jar
/opt/VFB/VFB_owl/lib/jdom-1.1.1.jar
/opt/VFB/VFB_owl/lib/jfact-1.0.0.jar
/opt/VFB/VFB_owl/lib/jline-0.9.93.jar
/opt/VFB/VFB_owl/lib/jpaul-2.5.1.jar
/opt/VFB/VFB_owl/lib/jython-standalone-2.7.0.jar
/opt/VFB/VFB_owl/lib/log4j-1.2.17.jar
/opt/VFB/VFB_owl/lib/more-reasoner-0.1.5-BBOP-1.jar
/opt/VFB/VFB_owl/lib/mysql-connector-java-5.1.26.jar
/opt/VFB/VFB_owl/lib/oboformat-tools-0.6.0.jar
/opt/VFB/VFB_owl/lib/oppl2-1.5.5.jar
/opt/VFB/VFB_owl/lib/org.osgi.core-1.4.0.jar
/opt/VFB/VFB_owl/lib/org.semanticweb.hermit-1.3.8.2.jar
/opt/VFB/VFB_owl/lib/owlapi-api-3.5.1.jar
/opt/VFB/VFB_owl/lib/owlapi-apibinding-3.5.1.jar
/opt/VFB/VFB_owl/lib/owlapi-distribution-3.4.8.jar
/opt/VFB/VFB_owl/lib/owlapi-impl-3.5.1.jar
/opt/VFB/VFB_owl/lib/owlapi-oboformat-3.5.1.jar
/opt/VFB/VFB_owl/lib/owlapi-parsers-3.5.1.jar
/opt/VFB/VFB_owl/lib/owlapi-tools-3.5.1.jar
/opt/VFB/VFB_owl/lib/parsers-1.5.2.jar
/opt/VFB/VFB_owl/lib/postgresql-9.3-1102-jdbc4.jar
/opt/VFB/VFB_owl/lib/slf4j-api-1.7.2.jar
/opt/VFB/VFB_owl/lib/slf4j-log4j12-1.7.2.jar
/opt/VFB/VFB_owl/lib/sparqldl-api-1.0.0.jar
/opt/VFB/VFB_owl/lib/trove4j-3.0.3.jar
```

**Comment by dosumis** [comment]
It feels like we're going round in circles on this (we've definitely had the whole thing working on at least one Edinburgh machine before). 

Are you still using all those cached jars?  Thought we removed them from the VFB_owl repo ages ago in favour of a maven build.

AFAIK, Heiko's forked version makes brain compatible with OWL-API v4.  You should be able to get all the OWL-API libs you need with a maven build that uses the pom on that repo.  I don't think these scripts have any dependency on OWLtools anymore.   This one certainly doesn't: owl2neo/add_anonymous_types.py

**Comment by dosumis** [comment]
Scratch that - Still at OWL_API v3.5 from dietze/brain.  But that begs the question of where v4 is coming from.   Is there an owltools import specified somewhere (I can't see it in pipeline/process.sh). If so, can you try turning it off?

**Comment by Robbie1977** [comment]
Brain generates only:

```
|-- README.md
|-- gen-key-script
|-- pom.xml
|-- src
|   |-- main
|   |   `-- java
|   |       `-- uk
|   |           `-- ac
|   |               `-- ebi
|   |                   `-- brain
|   |                       |-- core
|   |                       |   `-- Brain.java
|   |                       `-- error
|   |                           |-- BadNameException.java
|   |                           |-- BadPrefixException.java
|   |                           |-- BrainException.java
|   |                           |-- ClassExpressionException.java
|   |                           |-- DataPropertyExpressionException.java
|   |                           |-- DataRangeException.java
|   |                           |-- ExistingAnnotationPropertyException.java
|   |                           |-- ExistingClassException.java
|   |                           |-- ExistingDataPropertyException.java
|   |                           |-- ExistingEntityException.java
|   |                           |-- ExistingNamedIndividualException.java
|   |                           |-- ExistingObjectPropertyException.java
|   |                           |-- NamedIndividualException.java
|   |                           |-- NewOntologyException.java
|   |                           |-- NonExistingAnnotationPropertyException.java
|   |                           |-- NonExistingClassException.java
|   |                           |-- NonExistingDataPropertyException.java
|   |                           |-- NonExistingEntityException.java
|   |                           |-- NonExistingNamedIndividualException.java
|   |                           |-- NonExistingObjectPropertyException.java
|   |                           |-- ObjectPropertyExpressionException.java
|   |                           `-- StorageException.java
|   `-- test
|       |-- java
|       |   `-- uk
|       |       `-- ac
|       |           `-- ebi
|       |               |-- BrainPopulationTest.java
|       |               |-- BrainQueryTest.java
|       |               `-- BrainUtilsTest.java
|       `-- resources
|           |-- cars.jpg
|           |-- cars.owl
|           |-- catalog-v001.xml
|           |-- demo-out.owl
|           |-- demo.owl
|           |-- dev.owl
|           |-- disambiguate.owl
|           |-- go.owl
|           |-- individuals.owl
|           |-- output-prefix.owl
|           |-- output.owl
|           `-- prefix.owl
`-- target
    |-- Brain-1.5.2-SNAPSHOT.jar
    |-- Brain-1.5.2-SNAPSHOT.jar.asc
    |-- Brain-1.5.2-SNAPSHOT.pom
    |-- Brain-1.5.2-SNAPSHOT.pom.asc
    |-- classes
    |   `-- uk
    |       `-- ac
    |           `-- ebi
    |               `-- brain
    |                   |-- core
    |                   |   |-- Brain$ManchesterParser.class
    |                   |   `-- Brain.class
    |                   `-- error
    |                       |-- BadNameException.class
    |                       |-- BadPrefixException.class
    |                       |-- BrainException.class
    |                       |-- ClassExpressionException.class
    |                       |-- DataPropertyExpressionException.class
    |                       |-- DataRangeException.class
    |                       |-- ExistingAnnotationPropertyException.class
    |                       |-- ExistingClassException.class
    |                       |-- ExistingDataPropertyException.class
    |                       |-- ExistingEntityException.class
    |                       |-- ExistingNamedIndividualException.class
    |                       |-- ExistingObjectPropertyException.class
    |                       |-- NamedIndividualException.class
    |                       |-- NewOntologyException.class
    |                       |-- NonExistingAnnotationPropertyException.class
    |                       |-- NonExistingClassException.class
    |                       |-- NonExistingDataPropertyException.class
    |                       |-- NonExistingEntityException.class
    |                       |-- NonExistingNamedIndividualException.class
    |                       |-- NonExistingObjectPropertyException.class
    |                       |-- ObjectPropertyExpressionException.class
    |                       `-- StorageException.class
    |-- generated-sources
    |   `-- annotations
    |-- generated-test-sources
    |   `-- test-annotations
    |-- maven-archiver
    |   `-- pom.properties
    `-- test-classes
        |-- cars.jpg
        |-- cars.owl
        |-- catalog-v001.xml
        |-- demo-out.owl
        |-- demo.owl
        |-- dev.owl
        |-- disambiguate.owl
        |-- go.owl
        |-- individuals.owl
        |-- output-prefix.owl
        |-- output.owl
        |-- prefix.owl
        `-- uk
            `-- ac
                `-- ebi
                    |-- BrainPopulationTest.class
                    |-- BrainQueryTest.class
                    `-- BrainUtilsTest.class
```

**Comment by Robbie1977** [comment]
Should we adjust the version generated here to match brains requirements:
https://github.com/VirtualFlyBrain/VFB_owl/blob/master/pom.xml#L11

**Comment by dosumis** [comment]
Can this be closed?

**Comment by dosumis** [comment]
No longer relevant as dependence of pipeline on Brain library has been removed now Jython has been ditched.
