### ISSUE TITLE
Set up Jenkins jobs for automated update and checks of OWL files & DB

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_owl#5]
TODO: sort out secure server arrangements -  Ed or Cam?

**Comment by Robbie1977** [comment]
@dosumis Jenkins now updates GitHub on build - please check this is OK See https://github.com/VirtualFlyBrain/VFB_owl/commit/8e3bda98e731561f88e9d0384a1eb88692a6e781

**Comment by Robbie1977** [comment]
BTW is this common error during build ok?
<http://www.virtualflybrain.org/owl/VFB_00017880> <http://www.virtualflybrain.org/owl/VFB_00015869>)]
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:714)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:451)
	at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:376)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:182)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:146)
	at java.util.Arrays.sort(Arrays.java:472)
	at java.util.Collections.sort(Collections.java:155)
	at org.semanticweb.owlapi.util.CollectionFactory.sortOptionally(CollectionFactory.java:111)
	at org.coode.owlapi.functionalrenderer.OWLObjectRenderer.writeAxioms(OWLObjectRenderer.java:342)
	at org.coode.owlapi.functionalrenderer.OWLObjectRenderer.visit(OWLObjectRenderer.java:265)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyImpl.accept(OWLOntologyImpl.java:1516)
	at org.coode.owlapi.functionalrenderer.OWLFunctionalSyntaxOntologyStorer.storeOntology(OWLFunctionalSyntaxOntologyStorer.java:90)
	at org.semanticweb.owlapi.util.AbstractOWLOntologyStorer.store(AbstractOWLOntologyStorer.java:182)
	at org.semanticweb.owlapi.util.AbstractOWLOntologyStorer.storeOntology(AbstractOWLOntologyStorer.java:126)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1001)
	at owltools.io.ParserWrapper.saveOWL(ParserWrapper.java:206)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:3037)
	at owltools.cli.CommandRunner.run(CommandRunner.java:316)
	at owltools.cli.CommandRunner.run(CommandRunner.java:308)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)

Feb 20, 2015 5:50:22 PM org.semanticweb.owlapi.util.CollectionFactory sortOptionally
WARNING: Misbehaving triple comparator, leaving triples unsorted: [ObjectPropertyAssertion(<http://purl.obolibrary.org/obo/RO_0002351> <http://www.virtualflybrain.org/owl/VFB_00017890> <http://www.virtualflybrain.org/owl/VFB_00011064>),

**Comment by Robbie1977** [comment]
Also do you want me to add a commit to sandbox process on Jenkins?
Could also just do automatically on successful build?

**Comment by Robbie1977** [comment]
Do the other owl files such as Ito2013.owl need updating? (they are supplied under the owl directory)
